version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
   #   - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 764057086582.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI1=764057086582.dkr.ecr.ap-south-1.amazonaws.com/gaia-runner-app-demo
  build:
    commands:
      - echo Build started on $(date)
      - echo Building the Docker image...
      - docker build -t gaia-runner .
      - docker tag gaia-runner:latest $REPOSITORY_URI1:runner-1
  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI1:runner-1
      - printf '[{"name":"gaia-runner","imageUri":"764057086582.dkr.ecr.ap-south-1.amazonaws.com/gaia-runner-app-demo:runner-1"}]' >> imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
